<!DOCTYPE html>
<html lang="en">

<head>
    <title>"WCAG 2.0 HBBTV Test:1"</title>
    <link rel="stylesheet" type="text/css" href="./css/adaptable3.css" />
    <script src="../common_js/hbbtv.js"></script>
    <script src="../common_js/voice.js"></script>
    <script src="./js/softkey.js"></script>
    <script src="./js/adaptable3.js"></script>

    <!--meta http-equiv="content-type" content="application/vnd.hbbtv.xhtml+xml; charset=UTF-8" /-->
</head>

<body onload="adO3.init();">
    <div style="visibility: hidden; width: 0; height: 0;">
        <object type="application/oipfApplicationManager" id="appMan"></object>
    </div>

    <!-- viewable area -->
    <div id="viewable">
        <header class="titleArea" id="header" role="heading">
            <h4>Perceivable Test 3 Adaptable</h4>
            <p>Reference: WCAG 2.0 (1.3.3) Sensory Characteristics </p>
        </header>
        <div id="tspacer"></div>
        <div id="midBar">
            <div id="infoArea" tabindex="0" role="dialog" autofocus>
                <div id="infCont">
                    <h4>Background:</h4>
                    <p>This test demonstrates sensory characteristics. Color is used to indicate the form selection. The form and on screen keyboard have no html representation, but are defined using java script. The keyboard is a plugable module that is designed to test using the speech API based on 'bubbled' focus to the parent. Basic Aria roles are included to aid the screen reader.
                    </p>
                    <h4>Operation</h4>
                    <p> Press right to move to the input field.
                        <br/>Press ok on a field to launch the keyboard.
                        <br/>Enter your name in the Name field.
                        <br/>Enter your email in the Email Field.
                        <br/>Press ok on the Submit field to finish.</p>

                </div>
            </div>
            <div id="testArea" tabindex=-1>
                <!-- This application contains little html, the test area itself is generated by javascript
	       This is similar to initial applications views on live broadcast which have little html.
	       How this effects the use of voice guidance provided by the web speech API or an interpretted 
	       speech synthesiser is one aim for this test -->
            </div>

        </div>
        <div id="keyb"></div>
        <div id="bspacer">
        </div>
        <div id="footer">
            <div id="butbox">
                <div id="redb"></div>
                <div id="greenb"></div>
                <div id="yellowb"></div>
                <div id="cyanb"></div>
            </div>
        </div>
    </div>
</body>

</html>